(defun xxx (list)
  (do ((lst (cdr list)(cdr lst))
       (head (car list)(car lst))
       (lasthead list head)
      )
      ((null lst) NIL)
      (if (eq head lasthead)
          (return lst)
      )
  )
)
