(defun ematp (mat)
	(setf err 0)
	(if (not (quadmatp mat)) (error "Dimensions are wrong") 
		(setf dim (array-dimensions mat))
		(setf d (first dim))
		(dotimes (i d)
			(dotimes (j d)
				(setf value (aref mat i j))
				(if (= i j)
					(if (not (= value 1))
						(setf err 1)
					)
					(if (not (= value 0))
						(setf err 1)
					)
				)
			)
		)
		(if (= err 1)
			NIL T
		)

	)
)