(defun matmulmat (m1 m2)
  (setf dim1 (array-dimensions m1))
  (setf dim2 (array-dimensions m2))
  (setf ergm (make-array (list (first dim1) (second dim2)) :initial-element 0))
  (if (not (= (first dim1) (second dim2)))
      (error "Dimensionen passen nicht!")
      (dotimes (zeile (first dim1) ergm)
               (dotimes (spalte (second dim2))
                        (setf (aref ergm zeile spalte)
                              (do ((i 0 (+ i 1)) (sum 0))
                                  ((= i (first dim2)) sum)
                                  (setf sum (+ sum (* (aref m1 zeile i) 
                                                      (aref m2 i spalte))))
                              )
                        )
               )
      )
  )
)
