(defun quadmatp (m)
  (setf dim (array-dimensions m))
  (eq (first dim) (second dim))
)

(defun ematp (m)
  (setf dim (array-dimensions m))
  (setf err 0)
  (if (quadmatp m)
      (dotimes (zeile (first dim))
               (dotimes (spalte (second dim))
                        (setf wert (aref m zeile spalte))
                        (if (= zeile spalte)
                            (if (not (= wert 1))
                                (setf err 1)
                            )
                            (if (not (= wert 0))
                                (setf err 1)
                            )
                        )
               )
      )
      (error "Dimensionen passen nicht!")
  )
  (if (= err 1)
      NIL
      T
  )
)

(defun transpm (m)
  (setf dim (array-dimensions m))
  (setf newm (make-array (list (second dim) (first dim))))
  (dotimes (zeile (first dim) newm)
           (dotimes (spalte (second dim))
                    (setf (aref newm spalte zeile) (aref m zeile spalte))
           )
  )
)

(defun orthom (m)
  (ematp (matmulmat m (transpm m)))
)
